title: "askemata"
author: "Marcio L. M."
description: <a href='https://clustrmaps.com/site/1bwdo'  title='Visit tracker'><img src='//clustrmaps.com/map_v2.png?cl=cdd3e8&w=209&t=tt&d=fYCrZNCvpFifgkfasztQwZDOR21NJab0PJ5_nGtQ1XA&co=ffffff&ct=808080'/></a> # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "mlmiotto[arroba]gmail[.]com"
mastodon_username: "@askesis@qoto.org"
askesis_username: "https://askesis.hypotheses.org"
# twitter_username: "twitteruser"
github_username: "githubuser"
linkedin_username: "linkedinuser"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: "minima"

rss: rss

header_pages:
  - textos.md
  - archive.md
  - title: Group 1
    subfolderitems:
      - page: Thing 1
        url: /thing1.html
      - page: Thing 2
        url: /thing2.html
      - page: Thing 3
        url: /thing3.html
#  - "{% include search-lunr.html %}"

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
